# Generated by Django 4.1.5 on 2023-01-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
