# Generated by Django 4.1.6 on 2023-02-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_imagem_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
