# Generated by Django 4.1.5 on 2023-01-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_aluno_data_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='código_curos',
            new_name='código_curso',
        ),
    ]
