# Generated by Django 4.1.5 on 2023-01-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespetino'), ('N', 'Noturno')], default='M', max_length=1),
        ),
    ]
