# Generated by Django 4.1.5 on 2023-01-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_alter_matricula_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='celular',
            field=models.CharField(default='', max_length=13),
        ),
    ]
