# Generated by Django 4.1.5 on 2023-01-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_aluno_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
