# Generated by Django 4.1.5 on 2023-01-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('cpf', models.CharField(max_length=11)),
                ('celular', models.CharField(max_length=12)),
                ('data_nascimento', models.DateTimeField()),
                ('ativo', models.BooleanField()),
            ],
        ),
    ]
